### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by mrmagic2020** [Basssiiie/OpenRCT2-Simple-Typescript-Template#1]
When I tried to run `npm run build` in Terminal, it threw an error:

```
% npm run build

> openrct2-typescript-plugin@1.0.0 build
> npm run lint && rollup --config rollup.config.js --environment BUILD:production

npm ERR! Missing script: "lint"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm link # Symlink a package folder
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

Am I missing something, or is this a bug?

**Comment by Basssiiie** [comment]
Thank you for your report! This is indeed a bug, I forgot to remove the lint part from the command when I removed the rest of the related dependencies. It should be fixed now. :)

I'm not sure if it's suitable for you to update to the last version of the template, but it's also possible to just mimic my fix in your own `package.json` file.
